# Generated by Django 3.1.7 on 2021-03-10 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(default='', max_length=255)),
                ('room_jid', models.CharField(default='', max_length=255)),
                ('bbb_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.bbbchat')),
                ('bbb_live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.bbblive')),
                ('xmpp_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.xmppchat')),
            ],
        ),
    ]
