# Generated by Django 3.1.7 on 2021-03-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_streamfrontend'),
        ('stream', '0003_remove_stream_meeting_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='frontend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='children.streamfrontend'),
            preserve_default=False,
        ),
    ]
