# Generated by Django 3.1.7 on 2021-04-09 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(default='', max_length=255)),
                ('internal_meeting_id', models.CharField(default='', max_length=255)),
                ('rtmp_uri', models.CharField(default='', max_length=255)),
                ('bbb_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.bbbchat')),
                ('bbb_live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.bbblive')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.streamfrontend')),
            ],
            options={
                'unique_together': {('internal_meeting_id', 'bbb_chat'), ('meeting_id', 'bbb_chat')},
            },
        ),
    ]
