# Generated by Django 3.1.7 on 2021-03-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='meeting_password',
            field=models.CharField(default='ap', max_length=255),
        ),
        migrations.AddField(
            model_name='stream',
            name='rtmp_uri',
            field=models.CharField(default='', max_length=255),
        ),
    ]
