# Generated by Django 3.1.7 on 2021-03-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20210310_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='meeting_password',
        ),
    ]
