# Generated by Django 3.1.7 on 2021-03-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_streamfrontend'),
        ('stream', '0004_stream_frontend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('meeting_id', 'bbb_chat')},
        ),
    ]
