# Generated by Django 3.1.7 on 2021-04-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_auto_20210318_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='room_jid',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='xmpp_chat',
        ),
    ]
