# Generated by Django 3.1.7 on 2021-04-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_delete_xmppchat'),
        ('stream', '0006_auto_20210401_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='internal_meeting_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('meeting_id', 'bbb_chat'), ('internal_meeting_id', 'bbb_chat')},
        ),
    ]
