# Generated by Django 3.1.7 on 2021-04-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_streamfrontend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XmppChat',
        ),
    ]
