# Generated by Django 3.1.7 on 2021-05-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_streamchat_streamedge'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='frontend',
        ),
        migrations.AddField(
            model_name='channel',
            name='frontends',
            field=models.ManyToManyField(to='children.StreamFrontend'),
        ),
    ]
