# Generated by Django 3.2.2 on 2021-05-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20210507_1524'),
        ('api', '0002_auto_20210502_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='frontends',
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Channel2Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewers', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.channel')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.streamfrontend')),
            ],
        ),
    ]
