# Generated by Django 3.2.2 on 2021-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20210507_1524'),
        ('api', '0003_auto_20210507_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='frontends',
            field=models.ManyToManyField(through='api.Channel2Frontend', to='children.StreamFrontend'),
        ),
    ]
